/**
 * ublox.h
 */

#ifndef __UBLOX_H__
#define __UBLOX_H__


static atc_string_t UBLOX_CMD[] = {
    {ECHO_ON, (uint8_t *) "", (uint8_t *) "ATE1\r", 5,
     (uint8_t *) "", 0, (uint8_t *) "", 0, (uint8_t *) "", 0,
     (uint8_t *) ""},
    {ECHO_OFF, (uint8_t *) "", (uint8_t *) "ATE0\r", 5,
     (uint8_t *) "", 0, (uint8_t *) "", 0, (uint8_t *) "", 0,
     (uint8_t *) ""},
    {SET_ERR_VERSION, (uint8_t *) "", (uint8_t *) "AT+CMEE=2\r", 10,
     (uint8_t *) "", 0, (uint8_t *) "", 0, (uint8_t *) "", 0,
     (uint8_t *) ""},
    {IMEI_CHECK, (uint8_t *) "", (uint8_t *) "AT+CGSN\r", 8,
     (uint8_t *) "", 0,(uint8_t *) "", 0,
     (uint8_t *) " ", 0, (uint8_t *) ""},
    {PIN_STATUS, (uint8_t *) "", (uint8_t *) "AT+CPIN?\r", 9,
     (uint8_t *) "", 0, (uint8_t *) "+CPIN: READY", 12,
     (uint8_t *) "", 0, (uint8_t *) ""},
    {ICCID_CHECK, (uint8_t *) "", (uint8_t *) "AT+CCID?\r", 9,
     (uint8_t *) "", 0,(uint8_t *) "+CCID:", 6,
     (uint8_t *) "", 0, (uint8_t *) ""},
    {CSQ_QUAILTY, (uint8_t *) "", (uint8_t *) "AT+CSQ\r", 7,
     (uint8_t *) "", 0, (uint8_t *) "", 0, (uint8_t *) "+CSQ: ", 6,
     (uint8_t *) ""},
    {GPRS_STATUS, (uint8_t *) "", (uint8_t *) "AT+CGATT?\r", 10,
     (uint8_t *) "", 0, (uint8_t *) "+CGATT: ", 8, (uint8_t *) "",
     0, (uint8_t *) ""},
    {GSM_STATUS, (uint8_t *) "", (uint8_t *) "AT+COPS?\r", 9,
     (uint8_t *) "", 0, (uint8_t *) "", 0,
     (uint8_t *) "+COPS: 0,0,", 11, (uint8_t *) ""},
    {REGISTER_UN, (uint8_t *) "",
     (uint8_t *) "AT+UPSD=0,1,\"m2mapntest.tele2.com\"\r", 35, (uint8_t *) "", 0,
     (uint8_t *) "", 0, (uint8_t *) "", 0, (uint8_t *) ""},
    {REGISTER_CM, (uint8_t *) "",
     (uint8_t *) "AT+UPSD=0,1,\"CMNET\"\r", 20, (uint8_t *) "", 0,
     (uint8_t *) "", 0, (uint8_t *) "", 0, (uint8_t *) ""},
    {REQUIRE_IP_ADDR, (uint8_t *) "",
     (uint8_t *) "AT+UPSD=0,7,\"0.0.0.0\"\r", 0, (uint8_t *) "", 0,
     (uint8_t *) "", 0, (uint8_t *) "", 0, (uint8_t *) ""},
    {FLASH_GPRSCFG, (uint8_t *) "", (uint8_t *) "AT+UPSDA=0,1\r", 0,
     (uint8_t *) "", 0, (uint8_t *) "", 0, (uint8_t *) "", 0,
     (uint8_t *) ""},
    {ACTIVE_GPRS, (uint8_t *) "", (uint8_t *) "AT+UPSDA=0,3\r", 0,
     (uint8_t *) "", 0, (uint8_t *) "", 0, (uint8_t *) "", 0,
     (uint8_t *) ""},
    {CHECK_GPRS_STATUS, (uint8_t *) "",
     (uint8_t *) "AT+UPSND=0,0\r", 13, (uint8_t *) "", 0,
     (uint8_t *) "+UPSND: 0,0,", 12, (uint8_t *) "", 0,
     (uint8_t *) ""},
    {CHECK_GPRS_STATUS_R, (uint8_t *) "",
     (uint8_t *) "", 0, (uint8_t *) "", 0,
     (uint8_t *) "+UPSND: 0,0,", 12, (uint8_t *) "", 0,
     (uint8_t *) ""},
    {ACTIVE_GPRS_URC, (uint8_t *) "", (uint8_t *) "AT+CGREG=1\r", 11,
     (uint8_t *) "", 0, (uint8_t *) "", 0, (uint8_t *) "", 0,
     (uint8_t *) ""},
    {SOCKET_HEX, (uint8_t *) "", (uint8_t *) "AT+UDCONF=1,0\r", 0,
     (uint8_t *) "", 0, (uint8_t *) "", 0, (uint8_t *) "", 0,
     (uint8_t *) ""},
    {CHECK_HEX, (uint8_t *) "", (uint8_t *) "AT+UDCONF=1\r", 0,
     (uint8_t *) "", 0, (uint8_t *) "+UDCONF:", 8, (uint8_t *) "",
     0, (uint8_t *) ""},
    {CREATE_SOCKET, (uint8_t *) "", (uint8_t *) "AT+USOCR=", 9,
     (uint8_t *) "", 0, (uint8_t *) "+USOCR: ", 8, (uint8_t *) "",
     0, (uint8_t *) ""},
    {CREATE_SOCKET_CHECK, (uint8_t *) "", (uint8_t *) "", 0,
     (uint8_t *) "", 0, (uint8_t *) "+USOCR: ", 8, (uint8_t *) "",
     0, (uint8_t *) ""},
    {WRITE_HEAD, (uint8_t *) "", (uint8_t *) "AT+USOWR=", 9,
     (uint8_t *) "", 0, (uint8_t *) "@", 1, (uint8_t *) "", 0,
     (uint8_t *) ""},
    {WRITE_DATA, (uint8_t *) "", (uint8_t *) "", 0,
     (uint8_t *) "\r", 1, (uint8_t *) "+USOWR: ", 8, (uint8_t *) "",
     0, (uint8_t *) ""},
    {READ_DATA, (uint8_t *) "", (uint8_t *) "AT+USORD=", 9,
     (uint8_t *) "", 0, (uint8_t *) "+USORD: ", 8, (uint8_t *) "",
     0, (uint8_t *) ""},
    {READ_AGAIN, (uint8_t *) "", (uint8_t *) "", 0, (uint8_t *) "",
     0, (uint8_t *) "+USORD: ", 8, (uint8_t *) "", 0,
     (uint8_t *) ""},
    {CLOSE_SOCKET, (uint8_t *) "", (uint8_t *) "AT+USOCL=", 9,
     (uint8_t *) "", 0, (uint8_t *) "", 0, (uint8_t *) "", 0,
     (uint8_t *) ""},
    {SHUTDOWN_MODEM, (uint8_t *) "", (uint8_t *) "AT+CPWROFF\r", 11,
     (uint8_t *) "", 0, (uint8_t *) "", 0, (uint8_t *) "", 0,
     (uint8_t *) ""},
    {CONNECT_SOCKET, (uint8_t *) "CONNECT_SOCKET",
     (uint8_t *) "AT+USOCO=", 9, (uint8_t *) "", 0, (uint8_t *) "",
     0, (uint8_t *) "", 0, (uint8_t *) ""},
    {ADDR_INFO, (uint8_t *) "ADDR_INFO",
     (uint8_t *) "AT+UDNSRN=", 10, (uint8_t *) "", 0,
     (uint8_t *) "+UDNSRN: ", 9, (uint8_t *) "", 0, (uint8_t *) ""},
    {ADDR_INFO_CHECK, (uint8_t *) "ADDR_INFO_CHECK",
     (uint8_t *) "", 0, (uint8_t *) "", 0,
     (uint8_t *) "+UDNSRN: ", 9, (uint8_t *) "", 0, (uint8_t *) ""},
    {OK_CHECK, (uint8_t *) "OK_CHECK",
     (uint8_t *) "", 0, (uint8_t *) "", 0, (uint8_t *) "",
     0, (uint8_t *) "", 0, (uint8_t *) ""},

};

#define UBLOX_SOCKET_NUM 7
static uart_index_t uart_index;

static int32_t socket_available_num[UBLOX_SOCKET_NUM] = { 0 };

#endif                          /* __UBLOX_h__ */
